sirfz/tesserocr

- MANIFEST.in
This makes the source tarball on PyPI fit for packaging it for distributions
(Ubuntu, Debian, ...).
> Explicitly include README.rst and LICENSE in source tarball.

- MANIFEST.in
Tests won't work without it when downloading from PyPI.
> Include sample image in source tarball.

- tesseract4.pxd
- tesserocr.pyx
The API for TessPDFRendererCreate was changed about 9 days ago. I updated the tesserocr files to reflect the new changes which fixes compilation errors that popped up as a result. I've linked the relevant changes below for reference.
https://github.com/tesseract-ocr/tesseract/commit/8ce58ac458c78fa84ff77d2d74a3f51c2e5bd0a9#diff-1ff9fac4997a03321dc873248bcf1309
https://github.com/tesseract-ocr/tesseract/commit/effa5741e6ef8bcb37d68250ca39c92fae85f6a9#diff-0b21ad820cf950ff83875c63e6309107
> Update Tesseract 4 API

- setup.py
In Python 3, Popen.communicate() returns bytes strings, not literal strings. Therefore this comparison is necessary to avoid a bad detection of the version.
Python 3.6
>>> from subprocess import Popen, PIPE
>>> example = Popen(['ls'], stdout=PIPE)
>>> std, err = example.communicate()
>>> type(std)
<class 'bytes'>
>>> b'' == ''
False
Python 2.7
>>> from subprocess import Popen, PIPE
>>> example = Popen(['ls'], stdout=PIPE)
>>> std, err = example.communicate()
>>> type(std)
<type 'str'>
>>> b'' == ''
True
> Fix setup.py detecting Tesseract 4 as Tesseract 3 in Python 3

- README.rst
My Windows all-inclusive build has gained a lot of traction during the past couple of months. It is currently only linked on issue #19 ([here](https://github.com/sirfz/tesserocr/issues/19#issuecomment-335875716) and [here](https://github.com/sirfz/tesserocr/issues/19#issuecomment-374881553)). I typed up a short `Windows installation` section for the README to make **tesserocr** even more accessible to Windows users. What do you think? I'm looking forward to your feedback.
> added Windows installation to README

- setup.py
The version conversion to int is currently broken with the new tesseract versioning scheme which has removed the "0 padding" of the version fields, e.g. it is currently "4.0.0-beta1" rather than "4.00.00-alpha". So the latest 4.x version are detected as 3.x and are not compiling.
With this the detection should work again to detect tesseract 4.x.
> Fix version handling for new versioning scheme of tesseract

- tesserocr.pyx
If tesseract doesn't find a valid tessdata path during _api.Init(NULL, NULL), TessBaseAPI::GetInitLanguagesAsString() will return the empty string. This breaks PyTessBaseAPI(path=path/to/valid/tessdata/location) initialization since the default argument lang=_DEFAULT_LANG (which was set to '') is not a valid language.
Assumption: we moved our tessdata folder to some funky location where tesseract's [CCUtil::main_setup](https://github.com/tesseract-ocr/tesseract/blob/a07ee5c40bf958de26ba46175f97f23fe9e5fc2b/ccutil/mainblk.cpp) couldn't possibly find it.
In order to get the tessdata path and the default language provided by tesseract, tesserocr initializes the api with both the tessdata path as well as the language string set to `NULL` …
> fix for _DEFAULT_LANG not being set

- tesserocr.pyx
A change for handling the tessdata path has been discussed here https://github.com/tesseract-ocr/tesseract/pull/1328 and finally implemented via https://github.com/tesseract-ocr/tesseract/pull/1356. Before this change, the path passed to tesseract was appended with `"tessdata/"` by first setting the variable `m_data_sub_dir` in
[tesseract/ccutil/ccutil.h#L80](https://github.com/tesseract-ocr/tesseract/blob/80f51c3758fa872d14c008bc75dc991daf0669b7/ccutil/ccutil.h#L80):
```c++
STRING_VAR_H(m_data_sub_dir, "tessdata/", "Directory for data files");
```
and finally adding to the base path in
[tesseract/ccutil/mainblk.cpp#L104](https://github.com/tesseract-ocr/tesseract/blob/f0579380699c74ced74d1c64f23b602fc2517e0c/ccutil/mainblk.cpp#L104):
```c++
datadir += m_data_sub_dir;     /**< data …
```
> fix _DEFAULT_PATH for tesseract >= dba13db

- tests/test_api.py
Copying the fix from @bpotard provided in PR https://github.com/sirfz/tesserocr/pull/98 into [tesserocr/tests/test_api.py](https://github.com/sirfz/tesserocr/blob/99eac07dd527f856a8ab363763adfec3260e70dc/tests/test_api.py)
Also in `TestTessBaseApi.test_data_path()`
[tesserocr/tests/test_api.py#L111:](https://github.com/sirfz/tesserocr/blob/99eac07dd527f856a8ab363763adfec3260e70dc/tests/test_api.py#L111)
```python
new_path = os.path.abspath(os.path.join(path, os.path.pardir)) + os.path.sep
```
this will run into the same issues as https://github.com/sirfz/tesserocr/commit/3780d8d5958d0a38f61d9f3486994e9098041b62
> fixes for tests/test_api.py

- .travis.yml
- use prebuilt binaries from   https://github.com/nijel/tesseract-ocr-build
- no longer needs sudo on Travis CI
- currently 3.04.01 and 3.05.02 are tested
Currently it tests all combinations, what might be too much, please let me know if you want to reduce test matrix.
> Test against more tesseract versions

- .travis.yml
Update the tesseract to the last release. @nijel  already has the beta 4 binaries to Travis. This might heps tesserocr build with version 4 of tesseract to pass
> update tesseract version in travis, it may help the build pass

- README.rst
On a clean Ubuntu install you need to include ```apt install pkg-config``` before ```pip install tesserocr``` will work.
> Add pkg-config to Debian/Ubuntu requirements

- tesserocr.pyx
The zip returned by cdef func pixa_to_list produces a segfault in Python 3.x, where the zip builtin is generator-based. The segfault is avoided by returned a list instead.
> Patches segfault in pixa_to_list

- README.rst
Python 2.7 allows the use of `print()` with a single argument, which is used in most places in the README.
For places, where the newline is suppressed, `__future__ print_function` is used to make the code compatible with Python 3 and 2.7.
[With Python 2.7 being no longer maintained after Jan 1, 2020](https://pythonclock.org/), Python 3-compatible examples are going to become ever more important.
> Make README examples compatible with Python 3 and 2.7

- .travis.yml
Tesseract 4.1.0 is the latest stable release.
It no longer requires setting the locale environment variables.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Update Travis CI to Tesseract 4.1.0

- tesseract.pxd
- tesserocr.pyx
As of https://github.com/tesseract-ocr/tesseract/commit/cb0c024a6f92fd04c951add6cf7ff497625cfda0, Tesseract's API changed. This adapts to that change. I am _not_ at all sure how to check this still builds older Tesseract versions, though. Help is appreciated.
> replace STRING::string() by c_str()

- tesserocr.pyx
It was deleted in latest Tesseract 5 and unnecessary for older Tesseract versions.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Don't use assignment operator for TessBaseAPI

- tesserocr.pyx
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Fix memory leaks in GetComponentImages

- tests/test_api.py
There is a small typo in tests/test_api.py.
Should read `seconds` rather than `seocnds`.
> docs: Fix simple typo, seocnds -> seconds

- tesserocr.pyx
leptonica support BMB directly , for jpeg support it need external library. When leptonica is built without JPEG support pixa_to_list fails silently
> use BMP as fallback format (does not need external lib) instead of JPEG

- .travis.yml
- Windows.build.md
The old URL no longer works because the default branches for Tesseract
now use "main" instead of "master".
It's also better for tesserocr to use a tagged release to get model files
instead of getting the latest development version.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
> Get model files for Tesseract from tagged release 4.1.0

- Windows.build.md
There is a small typo in Windows.build.md.
Should read `installation` rather than `instalation`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, instalation -> installation

- .github/build-scripts/common-install-tesseract.sh
- .github/build-scripts/linux-install-tesseract.sh
- .github/build-scripts/macos-install-build-dependencies.sh
- .github/build-scripts/macos-install-tesseract.sh
- .github/build-scripts/manylinux-install-build-dependencies.sh
- .github/build-scripts/musllinux-install-build-dependencies.sh
- .github/workflows/build.yml
- pyproject.toml
resolves #123 
Hello.
This PR adds a github-workflow to create wheels containing all the required libraries.
builds include:
- python: 3.8-3.11
- os: linux and macos
This now builds `leptonica` and `tesseract` from source.
~~some further information tho:
since `tesseract` and `leptonica` are being installed via `yum` (for `manylinux`), `apk` (for `musllinux`) and `brew` (for `macos`) all of the built wheels contain  a different version of tesseract.
that might pose a problem to some.
i think the only way to get around that would be to compile tesseract from source.~~
> add github-workflow building wheels

- .github/workflows/build.yml
- use latest pypa/cibuildwheel for Python 3.12 support
> Add Python 3.12 wheels

- .github/workflows/build.yml
- enable emulated aarch64 build (fixes #322)
- build aarch64 in parallel as the emulation is quite slow
Test build at https://github.com/nijel/tesserocr/actions/runs/6403475167
Not ready to merge because tesseract fails to build, this has been already fixed upstream in  https://github.com/tesseract-ocr/tesseract/commit/d7c071197e771263e923b731af05302a7e68efbd, but it is not yet released.
>  add aarch64 wheels

- tesserocr.pyx
I found that the comments for `tessdata` path were misleading. They should be "tessdata", not the "parent of tessdata"
> Clarified the comments for tessdata path

- .github/workflows/build.yml
The old versions cause a warning:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3, actions/setup-python@v4.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Update several GitHub actions

- tesserocr.pyx
This PR exposes the full tesseract API initialization parameters in the `PyTessBaseAPI` constructor:
```python
api = PyTessBaseAPI(configs=["/path/to/my.config"], variables={"var_name": "var_value})
```
Check the `PyTessBaseAPI` docstring for details.
> Allow passing configs/variables on initialization

- .github/workflows/build.yml
Python 3.13 is released and it would be useful to ship wheels for it.
> Build Python 3.13 wheels

- .github/build-scripts/macos-install-tesseract.sh
- .github/workflows/build.yml
- use native GitHub workers instead of relying on emulation
- update cibuildwheel
- trigger workflow on pullrequests and branches as well to have them CI checkecked
> chore(ci): modernize wheel builds

- tesserocr/tesseract5.pxd
To be used in conjunction with https://github.com/tesseract-ocr/tesseract/pull/4420 – which hopefully will get merged in some form, ultimately.
There may be more functions that need exception conversion.
Example result:
```
15:36:15.156 ERROR ocrd.processor.base - Failure on page PHYS_0067: ELIST_ITERATOR::forward:Error:List would have returned a nullptr data pointer
Traceback (most recent call last):
File "/data/ocr-d/ocrd_all/core/src/ocrd/processor/base.py", line 710, in process_workspace_handle_page_task
task.result()
File "/data/ocr-d/ocrd_all/core/src/ocrd/processor/base.py", line 124, in result
return self.fn(*self.args, **self.kwargs)
File "/data/ocr-d/ocrd_all/core/src/ocrd/processor/base.py", line 1157, in _page_worker
_page_worker_processor.process_page_file(*input_files)
File …
```
> convert more exceptions
